### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by 4of92000** [superlou/fountain-atom#35]
I'm trying to use the PDF output generator built into the Fountain package and it doesn't work at all. It'd rather throw an error.

Steps to reproduce:

1. Make a Fountain document. Put some basic text into it. (Mine has a title page and some basic action and a scene header, but no dialogue.)
2. Hit Ctrl-Shift-m.

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Debian GNU/Linux 9
**Thrown From**: [fountain](https://github.com/superlou/fountain-atom) package 0.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /home/alexander/.atom/packages/fountain/lib/fountain.coffee:85

TypeError: Cannot read property 'split' of undefined
    at Object.pdfPreview (/packages/fountain/lib/fountain.coffee:85:84)
    at /packages/fountain/lib/fountain.coffee:32:31)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  2x -0:35 fountain:preview (input.hidden-input)
  2x -0:04.1.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
fountain 0.6.0 
language-latex 1.1.1 
language-racket 0.4.0 
language-scala 1.1.9 
language-scheme 1.4.0 
pdf-view 0.59.0 
python-tools 0.6.9 
```

**Comment by jrbostic** [comment]
@4of92000 Thanks for the thorough description.  I'm looking into this now.  When you say that it "doesn't work at all", do you mean that you get this error anytime you attempt to preview a fountain file?  Even preexisting files?  And this is the only error?  Do you get the same error if you attempt to export to PDF from the outline or using CTRL-ALT-SHIFT-X?

**Comment by 4of92000** [comment]
It doesn't throw an error when I save; instead, it opens a new tab with nothing in it. The same happens when I use Ctrl-Alt-Shift-X.

**Comment by jrbostic** [comment]
So, I have one more question... And this may sound silly, but... Was the editor with your fountain script in focus when you ran the command?  Like, was there an active cursor in it?

I ask because the place where you errored out is right after retrieving the file path from the active editor.  And your version of atom is using a newer version of the text buffer that actually fetches and sets the file in a function documented as "experimental"... 

So, I'm wondering if the problem is there or if a more robust approach to retrieving the path is required in newer releases of atom.

Also, was any text selected when you generated the PDF?  And was any file generated in the current directory when you exported to PDF?

**Comment by jrbostic** [comment]
So, I've confirmed the title issue for this ticket.  (Not really a common workflow for me to render an unsaved file, so it took a minute to realize that you can actually create an unpathed buffer instance.)  I was able to produce this in my current version of atom, and it's simply returning an undefined path, so that's addressable.  The possible solutions would be to either generate a default path or to refuse to render an unsaved file... but we can probably just make a best guess and shrug.

The secondary (real) issue, regarding rendering PDF in general, is more obscure.  I went so far as to borrow the laptop that my children use (running Ubuntu) and download atom 1.21.1... and indeed, the files do not generate, nor do all of the tests pass when a fresh branch is ran against this version of atom.  It appears that there's a silent breakdown somewhere in the pdf conversion promise chain.

It's seems unlikely to me now that the previously proposed explanation is the cause of these failures.  I can't say more until I've captured whatever failure state is being produced.

**Comment by superlou** [comment]
I think it would probably be ok to just not generate anything for now if it's not saved.  The assumption in the old preview code was that it would render based on what was saved.

I'm on Linux Mint with Atom 1.20.1 and it's working.  Do you think it's something to do with 1.21.x?

**Comment by jrbostic** [comment]
I'm inclined in that direction.  At this point, I don't know what else to think.  

I'll probably need to add logging during PDF creation to really nail down which piece.  There's child_process and fs modules as possible external culprits... But it could also be a change in an atom dependency/API (which probably would have already been captured by an issue)... Or something that's happening during the exec phase, where we use node to run the afterwriting conversion.

I'll update issue when I identify the source.  If it's on our end, then I'll submit a PR with a fix in the next few days (and maybe some better error reporting to help identify future issues faster).  If it's in atom or a dependency, I'll file an issue there and report back.

**Comment by jrbostic** [comment]
Okay, so it's the `child_process.exec` command.  I don't think it has anything to do with external plugins or deps or Atom.  The way it was written makes the assumption that node is installed globally.  I guess it didn't occur to me that Atom was using node internally without node on the OS global scope.  It just so happens that some of us have node installed already, so it would work as expected.

I'm thinking to try the suggested soultion of [installing a binary](https://stackoverflow.com/questions/14657170/installing-global-npm-dependencies-via-package-json) as this would only require adding a dependency and changing the node path in the exec string.  Never done it before, but I don't see any other way forward at the moment.

**Comment by superlou** [comment]
Could you use a [BufferedProcess](https://atom.io/docs/api/v1.9.0/BufferedProcess) rather than the dependency?

**Comment by jrbostic** [comment]
So, seems like we could use that to get the built in logging (if that's what you're after).  It looks like everything is there to put it in the promise chain.  The node thing would still be an issue though... However, it's subclass BufferedNodeProcess claims to provide the exact service we would need in addition to the logging.

This could make quick work of a solid fix.  Thanks for tracking that down.

**Comment by jrbostic** [comment]
@superlou See PR #36.  Added logging for standard out and error, so future issues can be more readily addressed.  Moved from `child_process.exec` to BufferedNodeProcess and added info notification if file not persisted.  Tests passing.

**Comment by jrbostic** [comment]
@superlou @4of92000 I've confirmed on my node-less Ubuntu machine that the preview and export are now working at version 0.6.1

**Comment by 4of92000** [comment]
Agreed. It works now.
