### ISSUE TITLE
Request: Emphasis

### ISSUE THREAD

**Issue by chbuschmann** [superlou/fountain-atom#4]
It would be wonderfull to have Atom display [emphasis](http://fountain.io/syntax#section-emphasis) much in the same way GitHub Markdown does: 
<img width="555" alt="screen shot 2016-06-26 at 21 39 06" src="https://cloud.githubusercontent.com/assets/9821670/16364407/715f1420-3be6-11e6-8668-460bb6847892.png">

**Comment by superlou** [comment]
@chbuschmann See release 0.4.0 and let me know if it's working.

**Comment by chbuschmann** [comment]
Great work! 

One issue remains:
<img width="720" alt="screen shot 2016-06-27 at 07 58 46" src="https://cloud.githubusercontent.com/assets/9821670/16370074/07238bb6-3c3d-11e6-9434-0ac4e8ef292c.png">
Perhaps it is by design but `_underline_` is rendering the same as `*bold*`. Perhaps it should distinguish it self somewhat?

**Comment by superlou** [comment]
It is somewhat by design.  Per the [Fountain spec for emphasis](http://fountain.io/syntax#section-emphasis), Fountain should follow markdown's rules for emphasis. For whatever reason, GFM prefers to italicize underlined text:

![default](https://cloud.githubusercontent.com/assets/709695/16378895/9128629c-3c3c-11e6-8ee6-4d70d18955da.png)

I left it as is in order to leave the compatibility with most Atom themes, since most handle the `markup italic gfm`.  However, if I manually add the underline class, it does show up underlined:

![underlined](https://cloud.githubusercontent.com/assets/709695/16378899/9600a3f6-3c3c-11e6-8416-9e7de6a584fb.png)

Would this be preferred behavior?  Does anyone know if this risks breaking any markdown functionality down the road?

**Comment by chbuschmann** [comment]
My OCD sorta demands it to be underlined for the sake of consistency, *but* I see the estetic of just having `_underlined_` as well and it is perfectly acceptable. Perhaps just leave it be for now?

**Comment by superlou** [comment]
I'm ok leaving it for now if you are.  I'm not 100% solid on the GFM grammar, and am a little afraid of aggravating an edge case.  We can always re-open if the Fountain spec. makes a recommendation or GFM rendering styles change.
